// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class LogParseResult {
    /**
     * Creates a new LogParseResult instance.
     * @param {Partial<LogParseResult>} [$$source = {}] - The source object to create the LogParseResult.
     */
    constructor($$source = {}) {
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }
        if (!("Addon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Addon"] = "";
        }
        if (!("File" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["File"] = "";
        }
        if (!("Error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogParseResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogParseResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogParseResult(/** @type {Partial<LogParseResult>} */($$parsedSource));
    }
}
