// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Addon {
    /**
     * Creates a new Addon instance.
     * @param {Partial<Addon>} [$$source = {}] - The source object to create the Addon.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commit"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("repo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["repo"] = "";
        }
        if (!("isManaged" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isManaged"] = false;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Addon instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Addon}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Addon(/** @type {Partial<Addon>} */($$parsedSource));
    }
}
