// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ApplicationRelease {
    /**
     * Creates a new ApplicationRelease instance.
     * @param {Partial<ApplicationRelease>} [$$source = {}] - The source object to create the ApplicationRelease.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationRelease instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplicationRelease}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationRelease(/** @type {Partial<ApplicationRelease>} */($$parsedSource));
    }
}
