// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../api/models.js";

/**
 * @returns {Promise<api$0.ApplicationRelease> & { cancel(): void }}
 */
export function GetLatestRelease() {
    let $resultPromise = /** @type {any} */($Call.ByID(794853741));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetVersion() {
    let $resultPromise = /** @type {any} */($Call.ByID(2470723901));
    return $resultPromise;
}

/**
 * @param {string} updateURL
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SelfUpdate(updateURL) {
    let $resultPromise = /** @type {any} */($Call.ByID(1317176842, updateURL));
    return $resultPromise;
}

/**
 * @param {string} token
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SetAuthToken(token) {
    let $resultPromise = /** @type {any} */($Call.ByID(3930936982, token));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = api$0.ApplicationRelease.createFrom;
