// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiagnoseIssues() {
  return window['go']['app']['App']['DiagnoseIssues']();
}

export function GetAddOns() {
  return window['go']['app']['App']['GetAddOns']();
}

export function GetAddonManifest() {
  return window['go']['app']['App']['GetAddonManifest']();
}

export function GetAddonManifests() {
  return window['go']['app']['App']['GetAddonManifests']();
}

export function GetConfigBool(arg1) {
  return window['go']['app']['App']['GetConfigBool'](arg1);
}

export function GetConfigString(arg1) {
  return window['go']['app']['App']['GetConfigString'](arg1);
}

export function GetLatestAddonRelease(arg1) {
  return window['go']['app']['App']['GetLatestAddonRelease'](arg1);
}

export function GetLatestApplicationRelease() {
  return window['go']['app']['App']['GetLatestApplicationRelease']();
}

export function GetReleases(arg1) {
  return window['go']['app']['App']['GetReleases'](arg1);
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function InstallAddon(arg1) {
  return window['go']['app']['App']['InstallAddon'](arg1);
}

export function IsAddonInstalled(arg1) {
  return window['go']['app']['App']['IsAddonInstalled'](arg1);
}

export function ResetAddonSettings() {
  return window['go']['app']['App']['ResetAddonSettings']();
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SetConfigBool(arg1, arg2) {
  return window['go']['app']['App']['SetConfigBool'](arg1, arg2);
}

export function SetConfigString(arg1, arg2) {
  return window['go']['app']['App']['SetConfigString'](arg1, arg2);
}

export function UninstallAddon(arg1) {
  return window['go']['app']['App']['UninstallAddon'](arg1);
}

export function UnmanageAddon(arg1) {
  return window['go']['app']['App']['UnmanageAddon'](arg1);
}
