// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ApplicationService from "./applicationservice.js";
import * as LocalAddonService from "./localaddonservice.js";
export {
    ApplicationService,
    LocalAddonService
};
