// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAddOns() {
  return window['go']['main']['App']['GetAddOns']();
}

export function GetAddonManifest(arg1) {
  return window['go']['main']['App']['GetAddonManifest'](arg1);
}

export function GetAddonManifests() {
  return window['go']['main']['App']['GetAddonManifests']();
}

export function GetConfigBool(arg1) {
  return window['go']['main']['App']['GetConfigBool'](arg1);
}

export function GetConfigString(arg1) {
  return window['go']['main']['App']['GetConfigString'](arg1);
}

export function GetLatestAddonRelease(arg1) {
  return window['go']['main']['App']['GetLatestAddonRelease'](arg1);
}

export function GetReleases(arg1) {
  return window['go']['main']['App']['GetReleases'](arg1);
}

export function InstallAddon(arg1) {
  return window['go']['main']['App']['InstallAddon'](arg1);
}

export function IsAddonInstalled(arg1) {
  return window['go']['main']['App']['IsAddonInstalled'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetConfigBool(arg1, arg2) {
  return window['go']['main']['App']['SetConfigBool'](arg1, arg2);
}

export function SetConfigString(arg1, arg2) {
  return window['go']['main']['App']['SetConfigString'](arg1, arg2);
}

export function UninstallAddon(arg1) {
  return window['go']['main']['App']['UninstallAddon'](arg1);
}
